# Generated by Django 3.2.8 on 2021-10-30 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='staus',
            new_name='status',
        ),
    ]
